version: "3"
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      - FLASK_DEBUG
      - APP_PORT=FLASK_APP_PORT
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE
      - MONGODB_CONNSTRING=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}?authSource=admin
    ports:
      - '8000:${FLASK_APP_PORT}'
    volumes: ['./api:/app']
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0.1
    restart: unless-stopped
    hostname: mongodb
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGODB_DATA_DIR='/data/db'
      - MONDODB_LOG_DIR='/dev/null'
    volumes:
      - ./mongodb/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
